version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@bd5rb8rq9nj2zwwc_medium?TNS_ADMIN=/app/oracle_wallet/
      - SPRING_DATASOURCE_USERNAME=FULLSTACKS6
      - SPRING_DATASOURCE_PASSWORD=ClaseFSI123-
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_SHOW_SQL=true
      - TNS_ADMIN=/app/wallet
    networks:
      - default

networks:
  default:
    driver: bridge



